import React from 'react';

const FieldRowIdContext = React.createContext<string>('');

/** Returns the stable id generated by the enclosing FieldRow for label association. */
export const useFieldId = (): string => React.useContext(FieldRowIdContext);

export function FieldRow({
  label,
  children,
}: {
  label: string;
  children: React.ReactNode;
}) {
  const id = React.useId();
  return (
    <FieldRowIdContext.Provider value={id}>
      <div style={styles.fieldRow}>
        <label htmlFor={id} style={styles.fieldLabel}>{label}</label>
        {children}
      </div>
    </FieldRowIdContext.Provider>
  );
}

const styles: Record<string, React.CSSProperties> = {
  fieldRow: {
    padding: '5px 12px',
    display: 'flex',
    flexDirection: 'column',
    gap: 3,
  },
  fieldLabel: {
    fontSize: 10,
    color: 'var(--color-fg-muted)',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
};
