import React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  panel: {
    display: 'flex',
    flexDirection: 'column',
    background: '#0f172a',
    borderLeft: '1px solid #1e293b',
    height: '100%',
    flexShrink: 0,
    overflow: 'hidden',
  },
  collapsedTab: {
    writingMode: 'vertical-rl',
    background: '#0f172a',
    border: 'none',
    borderLeft: '1px solid #1e293b',
    color: '#475569',
    cursor: 'pointer',
    padding: '8px 4px',
    fontSize: 11,
    flexShrink: 0,
  },
  panelHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '8px 12px',
    borderBottom: '1px solid #1e293b',
    background: '#0f172a',
    flexShrink: 0,
  },
  panelTitle: {
    fontWeight: 600,
    fontSize: 13,
    color: '#94a3b8',
  },
  panelHeaderActions: {
    display: 'flex',
    gap: 4,
  },
  headerBtn: {
    background: 'transparent',
    border: '1px solid #334155',
    color: '#64748b',
    cursor: 'pointer',
    borderRadius: 4,
    padding: '2px 6px',
    fontSize: 13,
    lineHeight: 1.4,
  },
  breadcrumb: {
    padding: '4px 12px',
    fontSize: 11,
    color: '#60a5fa',
    fontFamily: 'var(--font-family-mono)',
    background: '#0d1b2e',
    borderBottom: '1px solid #1e293b',
    flexShrink: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  readOnlyNotice: {
    padding: '5px 12px',
    background: '#0f1a2e',
    borderBottom: '1px solid #334155',
    fontSize: 11,
    color: '#64748b',
    letterSpacing: 0.4,
    flexShrink: 0,
  },
  panelBody: {
    flex: 1,
    overflowY: 'auto',
    padding: '0 0 16px',
  },
  sectionHeader: {
    padding: '8px 12px 4px',
    fontSize: 10,
    fontWeight: 700,
    color: '#475569',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    borderBottom: '1px solid #1e293b',
    marginTop: 4,
  },
  slotEditor: {
    borderBottom: '1px solid #1e293b',
    margin: '0 0',
  },
  slotEditorHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 4,
    padding: '5px 12px',
    cursor: 'pointer',
    userSelect: 'none',
  },
  slotEditorToggle: {
    color: '#475569',
    fontSize: 10,
    width: 10,
    flexShrink: 0,
  },
  slotEditorName: {
    color: '#e2e8f0',
    fontFamily: 'var(--font-family-mono)',
    fontSize: 12,
    flex: '0 1 auto',
  },
  slotEditorRange: {
    color: '#86efac',
    fontFamily: 'var(--font-family-mono)',
    fontSize: 11,
    flex: 1,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  slotEditorBadges: {
    display: 'flex',
    gap: 2,
    flexShrink: 0,
  },
  slotBadge: {
    fontSize: 9,
    background: '#334155',
    borderRadius: 3,
    padding: '0 3px',
    color: '#94a3b8',
  },
  slotEditorBody: {
    background: '#091120',
    paddingBottom: 6,
  },
  slotEditorActions: {
    padding: '4px 12px',
    display: 'flex',
    gap: 6,
  },
  addRow: {
    display: 'flex',
    gap: 6,
    padding: '6px 12px',
    alignItems: 'center',
  },
  importRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    padding: '3px 12px',
  },
  importPath: {
    flex: 1,
    fontFamily: 'var(--font-family-mono)',
    fontSize: 11,
    color: '#94a3b8',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  importRemoveBtn: {
    background: 'transparent',
    border: 'none',
    color: '#475569',
    cursor: 'pointer',
    padding: '1px 4px',
    fontSize: 11,
    borderRadius: 3,
    flexShrink: 0,
  },
  actionsRow: {
    padding: '8px 12px',
    display: 'flex',
    gap: 6,
    flexWrap: 'wrap',
  },
  btnPrimary: {
    background: '#1d4ed8',
    border: '1px solid #2563eb',
    color: '#fff',
    borderRadius: 4,
    padding: '4px 10px',
    fontSize: 12,
    cursor: 'pointer',
    flexShrink: 0,
  },
  btnDanger: {
    background: '#7f1d1d',
    border: '1px solid #991b1b',
    color: '#fca5a5',
    borderRadius: 4,
    padding: '4px 10px',
    fontSize: 12,
    cursor: 'pointer',
  },
  btnGhost: {
    background: 'transparent',
    border: '1px solid #334155',
    color: '#94a3b8',
    borderRadius: 4,
    padding: '4px 10px',
    fontSize: 12,
    cursor: 'pointer',
  },
  deleteConfirm: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    flexWrap: 'wrap',
  },
  deleteConfirmText: {
    fontSize: 12,
    color: '#fca5a5',
  },
  readOnlyValue: {
    fontFamily: 'var(--font-family-mono)',
    fontSize: 12,
    color: '#94a3b8',
    padding: '4px 0',
    display: 'block',
  },
  editableBadge: {
    margin: '4px 12px',
    display: 'inline-block',
    fontSize: 10,
    fontWeight: 600,
    color: '#86efac',
    background: '#064e3b',
    border: '1px solid #065f46',
    borderRadius: 4,
    padding: '1px 6px',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  edgeDescription: {
    fontSize: 11,
    color: '#64748b',
    fontFamily: 'sans-serif',
    fontStyle: 'italic',
    lineHeight: 1.4,
  },
  emptyPanel: {
    padding: '24px 16px',
    textAlign: 'center',
    color: '#475569',
  },
  emptyMessage: {
    fontSize: 13,
    fontWeight: 600,
    color: '#64748b',
    margin: '0 0 8px',
  },
  emptyHint: {
    fontSize: 11,
    margin: 0,
    lineHeight: 1.5,
  },
  slotRefRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    padding: '3px 12px',
    borderBottom: '1px solid #1e293b',
  },
  slotRefName: {
    fontFamily: 'var(--font-family-mono)',
    fontSize: 12,
    color: '#7dd3fc',
    flex: '0 1 auto',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  slotRefRange: {
    fontFamily: 'var(--font-family-mono)',
    fontSize: 11,
    color: '#86efac',
    flex: 1,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  slotRefMissing: {
    fontSize: 11,
    color: '#fbbf24',
    flex: 1,
  },
  slotRefRemoveBtn: {
    background: 'transparent',
    border: 'none',
    color: '#475569',
    cursor: 'pointer',
    padding: '1px 4px',
    fontSize: 11,
    borderRadius: 3,
    flexShrink: 0,
  },
};
