import React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  panel: {
    display: 'flex',
    flexDirection: 'column',
    background: 'var(--color-bg-canvas)',
    borderLeft: '1px solid var(--color-border-subtle)',
    height: '100%',
    flexShrink: 0,
    minWidth: 260,
    overflow: 'hidden',
  },
  collapsedTab: {
    writingMode: 'vertical-rl',
    background: 'var(--color-bg-canvas)',
    border: 'none',
    borderLeft: '1px solid var(--color-border-subtle)',
    color: 'var(--color-border-strong)',
    cursor: 'pointer',
    padding: '8px 4px',
    fontSize: 11,
    flexShrink: 0,
  },
  panelHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '8px 12px',
    borderBottom: '1px solid var(--color-border-subtle)',
    background: 'var(--color-bg-canvas)',
    flexShrink: 0,
  },
  panelTitle: {
    fontWeight: 600,
    fontSize: 13,
    color: 'var(--color-fg-secondary)',
  },
  panelHeaderActions: {
    display: 'flex',
    gap: 4,
  },
  headerBtn: {
    background: 'transparent',
    border: '1px solid var(--color-border-default)',
    color: 'var(--color-fg-muted)',
    cursor: 'pointer',
    borderRadius: 4,
    padding: '2px 6px',
    fontSize: 13,
    lineHeight: 1.4,
  },
  breadcrumb: {
    padding: '4px 12px',
    fontSize: 11,
    color: 'var(--color-accent-hover)',
    fontFamily: 'var(--font-family-mono)',
    background: 'var(--color-bg-surface-sunken)',
    borderBottom: '1px solid var(--color-border-subtle)',
    flexShrink: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  readOnlyNotice: {
    padding: '5px 12px',
    background: 'var(--color-bg-surface-sunken)',
    borderBottom: '1px solid var(--color-border-default)',
    fontSize: 11,
    color: 'var(--color-fg-muted)',
    letterSpacing: 0.4,
    flexShrink: 0,
  },
  panelBody: {
    flex: 1,
    overflowY: 'auto',
    padding: '0 0 16px',
  },
  sectionHeader: {
    padding: '8px 12px 4px',
    fontSize: 10,
    fontWeight: 700,
    color: 'var(--color-border-strong)',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    borderBottom: '1px solid var(--color-border-subtle)',
    marginTop: 4,
  },
  slotEditor: {
    borderBottom: '1px solid var(--color-border-subtle)',
    margin: '0 0',
  },
  slotEditorHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 4,
    padding: '5px 12px',
    cursor: 'pointer',
    userSelect: 'none',
  },
  slotEditorToggle: {
    color: 'var(--color-border-strong)',
    fontSize: 10,
    width: 10,
    flexShrink: 0,
  },
  slotEditorName: {
    color: 'var(--color-fg-primary)',
    fontFamily: 'var(--font-family-mono)',
    fontSize: 12,
    flex: '0 1 auto',
  },
  slotEditorRange: {
    color: 'var(--color-state-success-fg)',
    fontFamily: 'var(--font-family-mono)',
    fontSize: 11,
    flex: 1,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  slotEditorBadges: {
    display: 'flex',
    gap: 2,
    flexShrink: 0,
  },
  slotBadge: {
    fontSize: 9,
    background: 'var(--color-border-default)',
    borderRadius: 3,
    padding: '0 3px',
    color: 'var(--color-fg-secondary)',
  },
  slotEditorBody: {
    background: 'var(--color-bg-deep)',
    paddingBottom: 6,
  },
  slotEditorActions: {
    padding: '4px 12px',
    display: 'flex',
    gap: 6,
  },
  addRow: {
    display: 'flex',
    gap: 6,
    padding: '6px 12px',
    alignItems: 'center',
  },
  importRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    padding: '3px 12px',
  },
  importPath: {
    flex: 1,
    fontFamily: 'var(--font-family-mono)',
    fontSize: 11,
    color: 'var(--color-fg-secondary)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  importRemoveBtn: {
    background: 'transparent',
    border: 'none',
    color: 'var(--color-border-strong)',
    cursor: 'pointer',
    padding: '1px 4px',
    fontSize: 11,
    borderRadius: 3,
    flexShrink: 0,
  },
  actionsRow: {
    padding: '8px 12px',
    display: 'flex',
    gap: 6,
    flexWrap: 'wrap',
  },
  btnPrimary: {
    background: 'var(--color-accent-active)',
    border: '1px solid var(--color-border-focus)',
    color: 'var(--color-fg-on-accent)',
    borderRadius: 4,
    padding: '4px 10px',
    fontSize: 12,
    cursor: 'pointer',
    flexShrink: 0,
  },
  btnDanger: {
    background: 'var(--color-state-error-border)',
    border: '1px solid var(--color-state-error-bg)',
    color: 'var(--color-state-error-fg)',
    borderRadius: 4,
    padding: '4px 10px',
    fontSize: 12,
    cursor: 'pointer',
  },
  btnGhost: {
    background: 'transparent',
    border: '1px solid var(--color-border-default)',
    color: 'var(--color-fg-secondary)',
    borderRadius: 4,
    padding: '4px 10px',
    fontSize: 12,
    cursor: 'pointer',
  },
  deleteConfirm: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    flexWrap: 'wrap',
  },
  deleteConfirmText: {
    fontSize: 12,
    color: 'var(--color-state-error-fg)',
  },
  readOnlyValue: {
    fontFamily: 'var(--font-family-mono)',
    fontSize: 12,
    color: 'var(--color-fg-secondary)',
    padding: '4px 0',
    display: 'block',
  },
  editableBadge: {
    margin: '4px 12px',
    display: 'inline-block',
    fontSize: 10,
    fontWeight: 600,
    color: 'var(--color-state-success-fg)',
    background: 'var(--color-state-success-bg)',
    border: '1px solid var(--color-state-success-border)',
    borderRadius: 4,
    padding: '1px 6px',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  edgeDescription: {
    fontSize: 11,
    color: 'var(--color-fg-muted)',
    fontFamily: 'sans-serif',
    fontStyle: 'italic',
    lineHeight: 1.4,
  },
  emptyPanel: {
    padding: '24px 16px',
    textAlign: 'center',
    color: 'var(--color-border-strong)',
  },
  emptyMessage: {
    fontSize: 13,
    fontWeight: 600,
    color: 'var(--color-fg-muted)',
    margin: '0 0 8px',
  },
  emptyHint: {
    fontSize: 11,
    margin: 0,
    lineHeight: 1.5,
  },
  slotRefRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    padding: '3px 12px',
    borderBottom: '1px solid var(--color-border-subtle)',
  },
  slotRefName: {
    fontFamily: 'var(--font-family-mono)',
    fontSize: 12,
    color: 'var(--color-state-info-fg)',
    flex: '0 1 auto',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  slotRefRange: {
    fontFamily: 'var(--font-family-mono)',
    fontSize: 11,
    color: 'var(--color-state-success-fg)',
    flex: 1,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  slotRefMissing: {
    fontSize: 11,
    color: 'var(--color-state-warning)',
    flex: 1,
  },
  slotRefRemoveBtn: {
    background: 'transparent',
    border: 'none',
    color: 'var(--color-border-strong)',
    cursor: 'pointer',
    padding: '1px 4px',
    fontSize: 11,
    borderRadius: 3,
    flexShrink: 0,
  },
};
